In [1]:
import dateparser
import datetime
from collections import namedtuple
import CTLReader
import OBSReader
import os
import re
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [2]:
def extract_obs_data(path,filelist):
    records = []
    for file in filelist:
        obs = OBSReader.obs_from_file(path+os.sep+file)
        otime = OBSReader.P.search(file).group(2)
        time = dateparser.parse("20%s/%s/%s-%s:00:00"%(otime[:2],otime[2:4],otime[4:6],otime[6:8]))
        if hasattr(obs,'mean'):
            records.append(ObsSummary(
                date=time,
                temperature=obs.mean['temperatura'],
                dewp_temperature=obs.mean['dewp_temperatura'],
                pressure=obs.mean['pressure'],
                psl=obs.mean['psl'],
                humidity=obs.mean['humidity'],
                u_wind=obs.mean['u_wind'],
                v_wind=obs.mean['v_wind']))
            print('one record')
    return records

In [3]:
def derive_ntime_feature(df,feature,N):
    rows = df.shape[0]
    ntime_prior_measurements = [None]*N + [df[feature][i-N] for i in range(N,rows)]
    col_name = "{}_{}".format(feature,N)
    df[col_name] = ntime_prior_measurements

In [4]:
def forcast_in_guangdong(ctl,file):
    fcst = CTLReader.CTLReader(ctl,file)
    lon,lat=np.meshgrid(fcst.variables['longitude'][:].flatten(),
                        fcst.variables['latitude'][:].flatten())
    res = {}
    res['latitude'] = lat.flatten()
    res['longitude']= lon.flatten()
    res=pd.DataFrame(res)
    geometry = [Point(xy) for xy in zip(res.longitude,res.latitude)]
    crs = {'init':'epsg:4326'}
    data = gpd.GeoDataFrame(res,crs=crs,geometry=geometry)
    OBSReader.GUANGDONG.crs = data.crs
    datainner=gpd.sjoin(data,OBSReader.GUANGDONG,how='inner',op='within')
    return datainner.drop(['index_right','2000','DZZSTLSMJ'
                          ,'QLDJ','QLXS','XZQMC'],axis=1)

In [5]:
def forcast_to_result(ctl,file,lonlat_info):
    fcst = CTLReader.CTLReader(ctl,file)
    res = {}
    for var in need_to_read:
        res[var]=fcst.variables[var][:].flatten()
    res=pd.concat((lonlat_info,pd.DataFrame(res)),axis=1).dropna()
    return res.mean()

In [6]:
#获取观测结果
features   = ['date','temperature','dewp_temperature',
              'pressure','psl','humidity','u_wind','v_wind']
ObsSummary = namedtuple("ObsSummary",features)
need_to_read = ['t2m','ps','psl','u10m','v10m','rh2m','ts','cr']
ctl = os.path.abspath('./../read_binary/test.ctl')
file = os.path.abspath('./../read_binary/mars3km17040100001')
fcstpath = os.path.abspath('D:\data_mars3km_00f72/')
lonlat_in_guangdong = forcast_in_guangdong(ctl,file)

In [7]:
path = '/home/wenqs/data_synop04'
filelist = os.listdir(path)
filelist.sort()

FileNotFoundError: [Errno 2] No such file or directory: '/home/wenqs/data_synop04'

In [6]:
records = extract_obs_data(path,filelist)

/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_a'][missing_vals]
/home/wenqs/project_mlwf/main/OBSReader.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[col][missing_vals] = df[col+'_b'][missing_vals]

In [7]:
import pickle
#with open('records.pkl','wb') as fp:
#    pickle.dump(records,fp)

In [8]:
with open('records.pkl','rb') as fp:
    records=pickle.load(fp)

In [9]:
df = pd.DataFrame(records,columns=features).set_index('date')

In [10]:
fcst_features   = ['date','CombinedRadarReflective','SurfacePressure',
                   'SeaLevelPressure','RelativeHumidity2m','Temperature2m',
                   'SurfaceTemperature','U_wind10m','V_wind10m',
                   'CombinedRadarReflective_prefcst','SurfacePressure_prefcst',
                   'SeaLevelPressure_prefcst','RelativeHumidity2m_prefcst','Temperature2m_prefcst',
                   'SurfaceTemperature_prefcst','U_wind10m_prefcst','V_wind10m_prefcst']
FcstSummary = namedtuple("FcstSummary",fcst_features)

In [11]:
forcast_d = datetime.timedelta(days=1)
fcstpath = os.path.abspath('D:\data_mars3km_00f72/')

In [249]:
fcst_records=[]
for date in df.index:
    validtime = date.to_pydatetime()
    fcst_date_before=date.date() - forcast_d
    fcst_date=dateparser.parse(date.date().strftime("%Y/%m/%d-%H:%M:%S"))
    fcst_date_before=dateparser.parse(fcst_date_before.strftime("%Y/%m/%d-%H:%M:%S"))
    
    timedelta = validtime - fcst_date
    timedelta_before = validtime - fcst_date_before
    
    timedelta=int(timedelta.total_seconds()/3600)
    timedelta_before=int(timedelta_before.total_seconds()/3600)
    
    filename1=fcstpath+"%s%03d"%(fcst_date.strftime("%Y%m%d%H/mars3km%y%m%d%H"),timedelta)
    filename2=fcstpath+"%s%03d"%(fcst_date_before.strftime("%Y%m%d%H/mars3km%y%m%d%H"),timedelta_before)
    if os.path.isfile(filename1) and os.path.isfile(filename2):
        f1=forcast_to_result(ctl,filename1,lonlat_in_guangdong)
        f2=forcast_to_result(ctl,filename2,lonlat_in_guangdong)
        fcst_records.append(FcstSummary(
            date                   =validtime,
            CombinedRadarReflective=f1.cr,
            SurfacePressure        =f1.ps,
            SeaLevelPressure       =f1.psl,
            RelativeHumidity2m     =f1.rh2m,
            Temperature2m          =f1.t2m,
            SurfaceTemperature     =f1.ts,
            U_wind10m              =f1.u10m,
            V_wind10m              =f1.v10m,
            CombinedRadarReflective_prefcst=f2.cr,
            SurfacePressure_prefcst        =f2.ps,
            SeaLevelPressure_prefcst       =f2.psl,
            RelativeHumidity2m_prefcst     =f2.rh2m,
            Temperature2m_prefcst          =f2.t2m,
            SurfaceTemperature_prefcst     =f2.ts,
            U_wind10m_prefcst              =f2.u10m,
            V_wind10m_prefcst              =f2.v10m,
        ))

time: 1
time: 2
time: 3
time: 4
time: 5
time: 6
time: 7
time: 8
time: 9
time: 10
time: 11
time: 12
time: 13
time: 14
time: 15
time: 16
time: 17
time: 18
time: 19
time: 20
time: 21
time: 22
time: 23
time: 24
time: 25
time: 26
time: 27
time: 28
time: 29
time: 30
time: 31
time: 32
time: 33
time: 34
time: 35
time: 36
time: 37
time: 38
time: 39
time: 40
time: 41
time: 42
time: 43
time: 44
time: 45
time: 46
time: 47
time: 48
time: 49
time: 50
time: 51
time: 52
time: 53
time: 54
time: 55
time: 56
time: 57
time: 58
time: 59
time: 60
time: 61
time: 62
time: 63
time: 64
time: 65
time: 66
time: 67
time: 68
time: 69
time: 70
time: 71
time: 72
time: 73
time: 74
time: 75
time: 76
time: 77
time: 78
time: 79
time: 80
time: 81
time: 82
time: 83
time: 84
time: 85
time: 86
time: 87
time: 88
time: 89
time: 90
time: 91
time: 92
time: 93
time: 94
time: 95
time: 96
time: 97
time: 98
time: 99
time: 100
time: 101
time: 102
time: 103
time: 104
time: 105
time: 106
time: 107
time: 108
time: 109
time: 110
time: 111
time: 112
time: 113
time: 114
time: 115
time: 116
time: 117
time: 118
time: 119
time: 120
time: 121
time: 122
time: 123
time: 124
time: 125
time: 126
time: 127
time: 128
time: 129
time: 130
time: 131
time: 132
time: 133
time: 134
time: 135
time: 136
time: 137
time: 138
time: 139
time: 140
time: 141
time: 142
time: 143
time: 144
time: 145
time: 146
time: 147
time: 148
time: 149
time: 150
time: 151
time: 152
time: 153
time: 154
time: 155
time: 156
time: 157
time: 158
time: 159
time: 160
time: 161
time: 162
time: 163
time: 164
time: 165
time: 166
time: 167
time: 168
time: 169
time: 170
time: 171
time: 172
time: 173
time: 174
time: 175
time: 176
time: 177
time: 178
time: 179
time: 180
time: 181
time: 182
time: 183
time: 184
time: 185
time: 186
time: 187
time: 188
time: 189
time: 190
time: 191
time: 192
time: 193
time: 194
time: 195
time: 196
time: 197
time: 198
time: 199
time: 200
time: 201
time: 202
time: 203
time: 204
time: 205
time: 206
time: 207
time: 208
time: 209
time: 210
time: 211
time: 212
time: 213
time: 214
time: 215
time: 216
time: 217
time: 218
time: 219
time: 220
time: 221
time: 222
time: 223
time: 224
time: 225
time: 226
time: 227
time: 228
time: 229
time: 230
time: 231
time: 232
time: 233
time: 234
time: 235
time: 236
time: 237
time: 238
time: 239
time: 240
time: 241
time: 242
time: 243
time: 244
time: 245
time: 246
time: 247
time: 248
time: 249
time: 250
time: 251
time: 252
time: 253
time: 254
time: 255
time: 256
time: 257
time: 258
time: 259
time: 260
time: 261
time: 262
time: 263
time: 264
time: 265
time: 266
time: 267
time: 268
time: 269
time: 270
time: 271
time: 272
time: 273
time: 274
time: 275
time: 276
time: 277
time: 278
time: 279
time: 280
time: 281
time: 282
time: 283
time: 284
time: 285
time: 286
time: 287
time: 288
time: 289
time: 290
time: 291
time: 292
time: 293
time: 294
time: 295
time: 296
time: 297
time: 298
time: 299
time: 300
time: 301
time: 302
time: 303
time: 304
time: 305
time: 306
time: 307
time: 308
time: 309
time: 310
time: 311
time: 312
time: 313
time: 314
time: 315
time: 316
time: 317
time: 318
time: 319
time: 320
time: 321
time: 322
time: 323
time: 324
time: 325
time: 326
time: 327
time: 328
time: 329
time: 330
time: 331
time: 332
time: 333
time: 334
time: 335
time: 336
time: 337
time: 338
time: 339
time: 340
time: 341
time: 342
time: 343
time: 344
time: 345
time: 346
time: 347
time: 348
time: 349
time: 350
time: 351
time: 352
time: 353
time: 354
time: 355
time: 356
time: 357
time: 358
time: 359
time: 360
time: 361
time: 362
time: 363
time: 364
time: 365
time: 366
time: 367
time: 368
time: 369
time: 370
time: 371
time: 372
time: 373
time: 374
time: 375
time: 376
time: 377
time: 378
time: 379
time: 380
time: 381
time: 382
time: 383
time: 384
time: 385
time: 386
time: 387
time: 388
time: 389
time: 390
time: 391
time: 392
time: 393
time: 394
time: 395
time: 396
time: 397
time: 398
time: 399
time: 400
time: 401
time: 402
time: 403
time: 404
time: 405
time: 406
time: 407
time: 408
time: 409
time: 410
time: 411
time: 412
time: 413
time: 414
time: 415
time: 416
time: 417
time: 418
time: 419
time: 420
time: 421
time: 422
time: 423
time: 424
time: 425
time: 426
time: 427
time: 428
time: 429
time: 430
time: 431
time: 432
time: 433
time: 434
time: 435
time: 436
time: 437
time: 438
time: 439
time: 440
time: 441
time: 442
time: 443
time: 444
time: 445
time: 446
time: 447
time: 448
time: 449
time: 450
time: 451
time: 452
time: 453
time: 454
time: 455
time: 456
time: 457
time: 458
time: 459
time: 460
time: 461
time: 462
time: 463
time: 464
time: 465
time: 466
time: 467
time: 468
time: 469
time: 470
time: 471
time: 472
time: 473
time: 474
time: 475
time: 476
time: 477
time: 478
time: 479
time: 480
time: 481
time: 482
time: 483
time: 484
time: 485
time: 486
time: 487
time: 488
time: 489
time: 490
time: 491
time: 492
time: 493
time: 494
time: 495
time: 496
time: 497
time: 498
time: 499
time: 500
time: 501
time: 502
time: 503
time: 504
time: 505
time: 506
time: 507
time: 508
time: 509
time: 510
time: 511
time: 512
time: 513
time: 514
time: 515
time: 516
time: 517
time: 518
time: 519
time: 520
time: 521
time: 522
time: 523
time: 524
time: 525
time: 526
time: 527
time: 528
time: 529
time: 530
time: 531
time: 532
time: 533
time: 534
time: 535
time: 536
time: 537
time: 538
time: 539
time: 540
time: 541
time: 542
time: 543
time: 544
time: 545
time: 546
time: 547
time: 548
time: 549
time: 550
time: 551
time: 552
time: 553
time: 554
time: 555
time: 556
time: 557
time: 558
time: 559
time: 560
time: 561
time: 562
time: 563
time: 564
time: 565
time: 566
time: 567
time: 568
time: 569
time: 570
time: 571
time: 572
time: 573
time: 574
time: 575
time: 576
time: 577
time: 578
time: 579
time: 580
time: 581
time: 582
time: 583
time: 584
time: 585
time: 586
time: 587
time: 588
time: 589
time: 590
time: 591
time: 592
time: 593
time: 594
time: 595
time: 596
time: 597
time: 598
time: 599
time: 600
time: 601
time: 602
time: 603
time: 604
time: 605
time: 606
time: 607
time: 608
time: 609
time: 610
time: 611
time: 612
time: 613
time: 614
time: 615
time: 616
time: 617
time: 618
time: 619
time: 620
time: 621
time: 622
time: 623
time: 624
time: 625
time: 626
time: 627
time: 628
time: 629
time: 630
time: 631
time: 632
time: 633
time: 634
time: 635
time: 636
time: 637
time: 638
time: 639
time: 640
time: 641
time: 642
time: 643
time: 644
time: 645
time: 646
time: 647
time: 648
time: 649
time: 650
time: 651
time: 652
time: 653
time: 654
time: 655
time: 656
time: 657
time: 658
time: 659
time: 660
time: 661
time: 662
time: 663
time: 664
time: 665
time: 666
time: 667
time: 668
time: 669
time: 670
time: 671
time: 672
time: 673
time: 674
time: 675
time: 676
time: 677
time: 678
time: 679
time: 680
time: 681
time: 682
time: 683
time: 684
time: 685
time: 686
time: 687
time: 688
time: 689

In [252]:
#with open('fcst_records.pkl','wb') as fp:
#    pickle.dump(fcst_records,fp)

In [12]:
with open('fcst_records.pkl','rb') as fp:
    fcst_records=pickle.load(fp)

In [13]:
fcst_df = pd.DataFrame(fcst_records,columns=fcst_features).set_index('date')

#暂时不考虑雷达反射率回波
fcst_df = fcst_df.drop(['CombinedRadarReflective','CombinedRadarReflective_prefcst'],axis=1)

In [14]:
#分别获取观测与预报的分类信息
features_obs = list(df)
features_fcst= list(fcst_df)

In [15]:
#合并两份数据集
df_all = pd.concat([df,fcst_df],axis=1).dropna()
# 如果完全不引入模式预报
#df = df.dropna()
features_all=list(df_all)

In [16]:
#获取纯的模式预报结果
only_fcst=fcst_df[['Temperature2m','Temperature2m_prefcst']]

In [17]:
for feature in features_all:
    if feature != 'date':
        for N in range(1,4):
            derive_ntime_feature(df_all,feature,N)

In [18]:
# 排除不需要的实时变量  features_all
# 或者可以考虑只排除预报时刻的已知观测信息 features_obs
to_remove = [feature for feature in features_obs if feature not in ['temperature']]

In [19]:
to_save = [col for col in df_all.columns if col not in to_remove]
df_all = df_all[to_save]

In [20]:
spread = df_all.describe().T
IQR = spread['75%'] - spread['25%']
spread['outliers'] = (spread['min']<(spread['25%']-(3*IQR)))|(spread['max']>(spread['75%']+3*IQR))
spread.loc[spread.outliers,]

,count,mean,std,min,25%,50%,75%,max,outliers
RelativeHumidity2m,671.0,80.209165,21.220256,0.0000,75.295364,85.513954,94.213116,99.144684,True
u_wind_1,670.0,-0.421079,0.536775,-2.3168,-0.700493,-0.439780,-0.175425,1.426029,True
u_wind_2,669.0,-0.421076,0.537176,-2.3168,-0.700500,-0.440000,-0.174928,1.426029,True
u_wind_3,668.0,-0.420883,0.537555,-2.3168,-0.700540,-0.439780,-0.174462,1.426029,True
RelativeHumidity2m_1,670.0,80.190278,21.230465,0.0000,75.292080,85.508579,94.217184,99.144684,True
RelativeHumidity2m_2,669.0,80.169330,21.239419,0.0000,75.288795,85.503204,94.221252,99.144684,True
RelativeHumidity2m_3,668.0,80.149036,21.248843,0.0000,75.271202,85.473812,94.233212,99.144684,True

In [21]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib

In [24]:
df_all['RelativeHumidity2m'].hist(label='RelativeHumidity2m')
df_all['RelativeHumidity2m_prefcst'].hist(label='RelativeHumidity2m_prefcst')
plt.title('distribution of RelativeHumidity2m(0-24) and RelativeHumidity2m_prefcst(24-48)')

Text(0.5,1,'distribution of RelativeHumidity2m(0-24) and RelativeHumidity2m_prefcst(24-48)')

In [22]:
df_all = df_all.dropna()

In [23]:
corr=df_all.corr()[['temperature']].sort_values('temperature')
corr=corr[abs(corr)>0.6]
corr=corr.dropna()

In [24]:
print(corr)

                              temperature
SeaLevelPressure                -0.671090
SeaLevelPressure_prefcst        -0.656539
SurfacePressure                 -0.645180
SeaLevelPressure_1              -0.630928
SurfacePressure_prefcst         -0.629470
SeaLevelPressure_prefcst_1      -0.613689
SurfacePressure_1               -0.602984
U_wind10m                        0.605368
U_wind10m_3                      0.607103
U_wind10m_2                      0.612556
U_wind10m_1                      0.613194
v_wind_1                         0.616498
U_wind10m_prefcst_3              0.643260
U_wind10m_prefcst_2              0.657663
U_wind10m_prefcst_1              0.669611
U_wind10m_prefcst                0.676848
Temperature2m_prefcst_3          0.792047
SurfaceTemperature_prefcst_3     0.807475
temperature_3                    0.817180
Temperature2m_3                  0.820444
SurfaceTemperature_3             0.839467
Temperature2m_prefcst_2          0.871124
SurfaceTemperature_prefcst_2     0.876489
SurfaceTemperature_prefcst       0.882765
SurfaceTemperature               0.899591
Temperature2m_2                  0.900446
SurfaceTemperature_prefcst_1     0.904710
SurfaceTemperature_2             0.905353
temperature_2                    0.910425
Temperature2m_prefcst_1          0.917419
Temperature2m_prefcst            0.919976
SurfaceTemperature_1             0.928130
Temperature2m_1                  0.946357
Temperature2m                    0.947617
temperature_1                    0.974129
temperature                      1.000000

In [25]:
predictors = list(corr.drop(['temperature','v_wind_1','temperature_3','temperature_2','temperature_1'],axis=0).T)

In [26]:
predictors

['SeaLevelPressure',
 'SeaLevelPressure_prefcst',
 'SurfacePressure',
 'SeaLevelPressure_1',
 'SurfacePressure_prefcst',
 'SeaLevelPressure_prefcst_1',
 'SurfacePressure_1',
 'U_wind10m',
 'U_wind10m_3',
 'U_wind10m_2',
 'U_wind10m_1',
 'U_wind10m_prefcst_3',
 'U_wind10m_prefcst_2',
 'U_wind10m_prefcst_1',
 'U_wind10m_prefcst',
 'Temperature2m_prefcst_3',
 'SurfaceTemperature_prefcst_3',
 'Temperature2m_3',
 'SurfaceTemperature_3',
 'Temperature2m_prefcst_2',
 'SurfaceTemperature_prefcst_2',
 'SurfaceTemperature_prefcst',
 'SurfaceTemperature',
 'Temperature2m_2',
 'SurfaceTemperature_prefcst_1',
 'SurfaceTemperature_2',
 'Temperature2m_prefcst_1',
 'Temperature2m_prefcst',
 'SurfaceTemperature_1',
 'Temperature2m_1',
 'Temperature2m']

In [ ]:
#只考虑绝对值在0.6以上相关的变量，并且舍弃前一个观测时次的温度值

In [27]:
#predictors = ['temperatura_2','temperatura_3',
#              'dewp_temperatura_1','dewp_temperatura_2','dewp_temperatura_3',
#             'v_wind_1','psl_1']

df2 = df_all[['temperature'] + predictors]
df2 = df2.dropna()

In [28]:
import statsmodels.api as sm

X = df2[predictors]
y = df2['temperature']
X = sm.add_constant(X)
X.iloc[:5,:5]

C:\Users\wenqi\Anaconda3\envs\geopandas\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

,const,SeaLevelPressure,SeaLevelPressure_prefcst,SurfacePressure,SeaLevelPressure_1
date,,,,,
2017-04-01 03:00:00,1.0,1021.478699,1020.904419,1000.673523,1021.467590
2017-04-01 04:00:00,1.0,1021.223572,1020.327332,1000.481262,1021.478699
2017-04-01 05:00:00,1.0,1020.641357,1019.782043,999.947266,1021.223572
2017-04-01 06:00:00,1.0,1020.022400,1019.292725,999.358521,1020.641357
2017-04-01 07:00:00,1.0,1019.498962,1018.864990,998.842834,1020.022400

In [29]:
vf = True
while vf is True:
    model = sm.OLS(y,X).fit()
    pmax  = model.pvalues.max()
    if pmax > 0.05:
        X=X.drop(model.pvalues.idxmax(),axis=1)
    else:
        vf = False

In [30]:
X

,const,SeaLevelPressure_prefcst,SurfacePressure_prefcst,U_wind10m_1,U_wind10m_prefcst_3,U_wind10m_prefcst_2,U_wind10m_prefcst,Temperature2m_prefcst_3,SurfaceTemperature_prefcst_3,Temperature2m_3,Temperature2m_prefcst_2,SurfaceTemperature_prefcst_2,SurfaceTemperature_prefcst,Temperature2m
date,,,,,,,,,,,,,,
2017-04-01 03:00:00,1.0,1020.904419,1000.101624,-3.361407,-3.351451,-3.554580,-3.502501,286.525116,287.688507,287.477295,288.177856,289.928650,293.958038,291.890320
2017-04-01 04:00:00,1.0,1020.327332,999.595276,-3.659685,-3.554580,-3.543207,-3.476880,288.177856,289.928650,288.587433,289.854004,292.076172,295.417419,293.275085
2017-04-01 05:00:00,1.0,1019.782043,999.099426,-3.798199,-3.543207,-3.502501,-3.479424,289.854004,292.076172,290.279663,291.488586,293.958038,296.365479,294.355225
2017-04-01 06:00:00,1.0,1019.292725,998.638855,-3.903121,-3.502501,-3.476880,-3.495173,291.488586,293.958038,291.890320,292.948853,295.417419,296.815887,295.102448
2017-04-01 07:00:00,1.0,1018.864990,998.218994,-4.022787,-3.476880,-3.479424,-3.503056,292.948853,295.417419,293.275085,294.109497,296.365479,296.774719,295.485321
2017-04-01 08:00:00,1.0,1018.815308,998.149292,-4.130190,-3.479424,-3.495173,-3.570184,294.109497,296.365479,294.355225,294.923157,296.815887,296.210968,295.482849
2017-04-01 09:00:00,1.0,1018.774048,998.065918,-4.206345,-3.495173,-3.503056,-3.609655,294.923157,296.815887,295.102448,295.365021,296.774719,295.124908,295.022797
2017-04-01 10:00:00,1.0,1018.910339,998.133728,-4.171447,-3.503056,-3.570184,-3.204129,295.365021,296.774719,295.485321,295.411652,296.210968,293.549713,293.950836
2017-04-01 11:00:00,1.0,1019.248962,998.359131,-3.583307,-3.570184,-3.609655,-2.863504,295.411652,296.210968,295.482849,294.997192,295.124908,291.053925,291.706238
2017-04-01 12:00:00,1.0,1019.630066,998.671265,-3.154392,-3.609655,-3.204129,-2.897209,294.997192,295.124908,295.022797,293.933197,293.549713,289.869507,290.544983
2017-04-01 13:00:00,1.0,1019.905396,998.887024,-3.145291,-3.204129,-2.863504,-2.919235,293.933197,293.549713,293.950836,291.637756,291.053925,289.144531,289.810242
2017-04-01 14:00:00,1.0,1019.835266,998.770142,-3.134634,-2.863504,-2.897209,-2.868763,291.637756,291.053925,291.706238,290.455048,289.869507,288.576904,289.235870
2017-04-02 00:00:00,1.0,1023.165955,1002.119934,-3.098574,-2.897209,-2.919235,-3.764654,290.455048,289.869507,290.544983,289.709412,289.144531,289.495209,287.939148
2017-04-02 01:00:00,1.0,1023.016418,1002.111511,0.000000,-2.919235,-2.868763,-4.158174,289.709412,289.144531,289.810242,289.125244,288.576904,292.335144,291.387787
2017-04-02 02:00:00,1.0,1022.446045,1001.647461,-3.680355,-2.868763,-3.764654,-4.355518,289.125244,288.576904,289.235870,288.844940,289.495209,294.613342,292.857666
2017-04-02 03:00:00,1.0,1021.936096,1001.217651,-4.317530,-3.764654,-4.158174,-4.431736,288.844940,289.495209,287.939148,291.057709,292.335144,296.288269,294.066833
2017-04-02 04:00:00,1.0,1021.388306,1000.729553,-4.704293,-4.158174,-4.355518,-4.415243,291.057709,292.335144,291.387787,292.883514,294.613342,297.439484,295.054047
2017-04-02 05:00:00,1.0,1020.848633,1000.230713,-4.791078,-4.355518,-4.431736,-4.348498,292.883514,294.613342,292.857666,294.298706,296.288269,298.116913,295.781342
2017-04-02 06:00:00,1.0,1020.334045,999.738159,-4.727364,-4.431736,-4.415243,-4.258915,294.298706,296.288269,294.066833,295.354218,297.439484,298.322144,296.193848
2017-04-02 07:00:00,1.0,1019.955750,999.359436,-4.671208,-4.415243,-4.348498,-4.155199,295.354218,297.439484,295.054047,296.110291,298.116913,298.052917,296.338104
2017-04-02 08:00:00,1.0,1019.904358,999.281250,-4.666222,-4.348498,-4.258915,-4.079248,296.110291,298.116913,295.781342,296.570496,298.322144,297.294708,296.155090
2017-04-02 09:00:00,1.0,1019.850952,999.178223,-4.668345,-4.258915,-4.155199,-3.967392,296.570496,298.322144,296.193848,296.722961,298.052917,296.017334,295.526550
2017-04-02 10:00:00,1.0,1019.892090,999.144104,-4.577435,-4.155199,-4.079248,-3.598451,296.722961,298.052917,296.338104,296.543213,297.294708,294.227844,294.263641
2017-04-02 11:00:00,1.0,1020.081604,999.221863,-4.083939,-4.079248,-3.967392,-3.113081,296.543213,297.294708,296.155090,295.943848,296.017334,291.736237,291.919006
2017-04-02 12:00:00,1.0,1020.288086,999.365479,-3.585562,-3.967392,-3.598451,-3.126633,295.943848,296.017334,295.526550,294.718475,294.227844,290.505798,290.719574
2017-04-02 13:00:00,1.0,1020.410522,999.444397,-3.563956,-3.598451,-3.113081,-3.053048,294.718475,294.227844,294.263641,292.359894,291.736237,289.750824,289.957001
2017-04-02 14:00:00,1.0,1020.298096,999.296021,-3.447134,-3.113081,-3.126633,-2.881009,292.359894,291.736237,291.919006,291.127960,290.505798,289.169830,289.360809
2017-04-02 15:00:00,1.0,1020.316650,999.277344,-3.220515,-3.126633,-3.053048,-2.758280,291.127960,290.505798,290.719574,290.336914,289.750824,288.692413,288.881683
2017-04-02 16:00:00,1.0,1020.413513,999.335815,-3.030725,-3.053048,-2.881009,-2.671610,290.336914,289.750824,289.957001,289.717957,289.169830,288.280396,288.484894
2017-04-02 17:00:00,1.0,1020.502441,999.391968,-2.938443,-2.881009,-2.758280,-2.627767,289.717957,289.169830,289.360809,289.221313,288.692413,287.930878,288.130127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-04-29 18:00:00,1.0,1013.548950,992.802551,-0.155384,-0.523884,-0.347531,-0.051885,293.321930,292.825714,293.147339,292.926605,292.436310,291.811493,292.148499
2017-04-29 19:00:00,1.0,1013.683838,992.922974,-0.075352,-0.347531,-0.185640,0.034102,292.926605,292.436310,292.754517,292.593658,292.101562,291.562622,291.911743
2017-04-29 20:00:00,1.0,1014.031494,993.253601,0.011080,-0.185640,-0.051885,0.033285,292.593658,292.101562,292.423737,292.316101,291.811493,291.349487,291.715179
2017-04-29 21:00:00,1.0,1014.294128,993.501892,0.042278,-0.051885,0.034102,-0.009641,292.316101,291.811493,292.148499,292.081696,291.562622,291.170288,291.550659
2017-04-29 22:00:00,1.0,1014.484009,993.686218,0.033645,0.034102,0.033285,-0.083941,292.081696,291.562622,291.911743,291.888031,291.349487,291.129974,291.412811
2017-04-29 23:00:00,1.0,1014.588379,993.860413,-0.034400,0.033285,-0.009641,-0.161839,291.888031,291.349487,291.715179,291.719879,291.170288,292.817413,292.593201
2017-04-30 00:00:00,1.0,1014.494934,993.881897,-0.134000,-0.009641,-0.083941,-0.250104,291.719879,291.170288,291.550659,291.569366,291.129974,295.826935,294.125122
2017-04-30 01:00:00,1.0,1014.298096,993.785095,0.000000,-0.083941,-0.161839,-0.204376,291.569366,291.129974,291.412811,292.733521,292.817413,298.252930,297.115234
2017-04-30 02:00:00,1.0,1013.759338,993.331787,-0.308382,-0.161839,-0.250104,-0.077139,292.733521,292.817413,292.593201,294.883911,295.826935,300.093353,298.392975
2017-04-30 03:00:00,1.0,1013.213013,992.853271,-0.269688,-0.250104,-0.204376,0.000703,294.883911,295.826935,294.125122,296.655304,298.252930,301.444519,299.461365
2017-04-30 04:00:00,1.0,1012.644897,992.333130,-0.139840,-0.204376,-0.077139,0.026727,296.655304,298.252930,297.115234,298.066040,300.093353,302.293335,300.279419
2017-04-30 05:00:00,1.0,1012.052551,991.770020,-0.000818,-0.077139,0.000703,-0.008421,298.066040,300.093353,298.392975,299.224152,301.444519,302.651917,300.715973
2017-04-30 06:00:00,1.0,1011.478394,991.204224,0.092125,0.000703,0.026727,-0.119233,299.224152,301.444519,299.461365,300.100861,302.293335,302.509155,300.754456
2017-04-30 07:00:00,1.0,1011.049377,990.762634,0.017620,0.026727,-0.008421,-0.302858,300.100861,302.293335,300.279419,300.690704,302.651917,301.937439,300.549591
2017-04-30 08:00:00,1.0,1011.012451,990.693542,-0.155673,-0.008421,-0.119233,-0.572287,300.690704,302.651917,300.715973,300.949280,302.509155,301.004456,300.055878
2017-04-30 09:00:00,1.0,1010.983215,990.616333,-0.431361,-0.119233,-0.302858,-0.864595,300.949280,302.509155,300.754456,300.876801,301.937439,299.737305,299.370300
2017-04-30 10:00:00,1.0,1011.083069,990.652588,-0.706086,-0.302858,-0.572287,-1.159789,300.876801,301.937439,300.549591,300.483185,301.004456,298.202789,298.357666
2017-04-30 11:00:00,1.0,1011.322144,990.809265,-0.968698,-0.572287,-0.864595,-1.322888,300.483185,301.004456,300.055878,299.736145,299.737305,296.287933,296.698792
2017-04-30 12:00:00,1.0,1011.662354,991.095215,-1.158804,-0.864595,-1.159789,-1.462467,299.736145,299.737305,299.370300,298.592407,298.202789,295.138489,295.559814
2017-04-30 13:00:00,1.0,1011.916687,991.315918,-1.331760,-1.159789,-1.322888,-1.510988,298.592407,298.202789,298.357666,296.796783,296.287933,294.473907,294.873444
2017-04-30 14:00:00,1.0,1011.837769,991.214966,-1.408210,-1.322888,-1.462467,-1.469918,296.796783,296.287933,296.698792,295.628906,295.138489,293.970276,294.346649
2017-04-30 15:00:00,1.0,1011.924377,991.281006,-1.370662,-1.462467,-1.510988,-1.379455,295.628906,295.138489,295.559814,294.923828,294.473907,293.573242,293.949921
2017-04-30 16:00:00,1.0,1012.003540,991.343628,-1.279005,-1.510988,-1.469918,-1.291376,294.923828,294.473907,294.873444,294.395660,293.970276,293.270721,293.631104
2017-04-30 17:00:00,1.0,1012.091431,991.417908,-1.187018,-1.469918,-1.379455,-1.223186,294.395660,293.970276,294.346649,293.993225,293.573242,293.045105,293.364349
2017-04-30 18:00:00,1.0,1012.192139,991.508179,-1.112559,-1.379455,-1.291376,-1.147184,293.993225,293.573242,293.949921,293.691498,293.270721,292.880554,293.168274
2017-04-30 19:00:00,1.0,1012.419617,991.724854,-1.045764,-1.291376,-1.223186,-1.041798,293.691498,293.270721,293.631104,293.469299,293.045105,292.773834,293.045502
2017-04-30 20:00:00,1.0,1012.956055,992.247742,-0.967393,-1.223186,-1.147184,-0.966318,293.469299,293.045105,293.364349,293.306763,292.880554,292.711243,292.977875
2017-04-30 21:00:00,1.0,1013.302368,992.585510,-0.930145,-1.147184,-1.041798,-0.951282,293.306763,292.880554,293.168274,293.200073,292.773834,292.667389,292.943756
2017-04-30 22:00:00,1.0,1013.569214,992.848022,-0.931496,-1.041798,-0.966318,-0.988776,293.200073,292.773834,293.045502,293.141266,292.711243,292.696747,292.936859
2017-04-30 23:00:00,1.0,1013.741028,993.057556,-0.992538,-0.966318,-0.951282,-1.054235,293.141266,292.711243,292.977875,293.101868,292.667389,293.832092,293.739899

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X = X.drop('const',axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=12)

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
regressor = LinearRegression()
regressor.fit(X_train,y_train)
prediction = regressor.predict(X_test)

In [37]:
with open('regressor.pkl','wb') as fp:
    pickle.dump(regressor,fp)

with open('X_test.pkl','wb') as fp:
    pickle.dump(X_test,fp)

In [98]:
res = pd.concat([y_test,pd.DataFrame({'end var':prediction},index=y_test.index)],axis=1)
res = pd.concat([res,only_fcst],axis=1).dropna()
res = res - 273.15

In [99]:
res.plot()

In [88]:
pd.concat([res,only_fcst],axis=1)

,temperature,end var,Temperature2m,Temperature2m_prefcst
date,,,,
2017-04-01 00:00:00,NaN,NaN,287.477295,286.525116
2017-04-01 01:00:00,NaN,NaN,288.587433,288.177856
2017-04-01 02:00:00,NaN,NaN,290.279663,289.854004
2017-04-01 03:00:00,NaN,NaN,291.890320,291.488586
2017-04-01 04:00:00,NaN,NaN,293.275085,292.948853
2017-04-01 05:00:00,NaN,NaN,294.355225,294.109497
2017-04-01 06:00:00,295.432222,294.751549,295.102448,294.923157
2017-04-01 07:00:00,NaN,NaN,295.485321,295.365021
2017-04-01 08:00:00,NaN,NaN,295.482849,295.411652
2017-04-01 09:00:00,NaN,NaN,295.022797,294.997192
2017-04-01 10:00:00,NaN,NaN,293.950836,293.933197
2017-04-01 11:00:00,NaN,NaN,291.706238,291.637756
2017-04-01 12:00:00,NaN,NaN,290.544983,290.455048
2017-04-01 13:00:00,290.023855,290.743626,289.810242,289.709412
2017-04-01 14:00:00,289.177722,290.247581,289.235870,289.125244
2017-04-02 00:00:00,NaN,NaN,287.939148,288.844940
2017-04-02 01:00:00,NaN,NaN,291.387787,291.057709
2017-04-02 02:00:00,293.285882,293.704908,292.857666,292.883514
2017-04-02 03:00:00,NaN,NaN,294.066833,294.298706
2017-04-02 04:00:00,NaN,NaN,295.054047,295.354218
2017-04-02 05:00:00,NaN,NaN,295.781342,296.110291
2017-04-02 06:00:00,NaN,NaN,296.193848,296.570496
2017-04-02 07:00:00,NaN,NaN,296.338104,296.722961
2017-04-02 08:00:00,297.488169,296.071540,296.155090,296.543213
2017-04-02 09:00:00,NaN,NaN,295.526550,295.943848
2017-04-02 10:00:00,NaN,NaN,294.263641,294.718475
2017-04-02 11:00:00,NaN,NaN,291.919006,292.359894
2017-04-02 12:00:00,NaN,NaN,290.719574,291.127960
2017-04-02 13:00:00,NaN,NaN,289.957001,290.336914
2017-04-02 14:00:00,NaN,NaN,289.360809,289.717957
...,...,...,...,...
2017-04-29 18:00:00,292.390556,293.253881,292.148499,292.316101
2017-04-29 19:00:00,NaN,NaN,291.911743,292.081696
2017-04-29 20:00:00,291.529863,292.768796,291.715179,291.888031
2017-04-29 21:00:00,291.529444,292.588724,291.550659,291.719879
2017-04-29 22:00:00,NaN,NaN,291.412811,291.569366
2017-04-29 23:00:00,NaN,NaN,292.593201,292.733521
2017-04-30 00:00:00,NaN,NaN,294.125122,294.883911
2017-04-30 01:00:00,NaN,NaN,297.115234,296.655304
2017-04-30 02:00:00,NaN,NaN,298.392975,298.066040
2017-04-30 03:00:00,NaN,NaN,299.461365,299.224152
2017-04-30 04:00:00,NaN,NaN,300.279419,300.100861
2017-04-30 05:00:00,300.657500,300.648540,300.715973,300.690704
2017-04-30 06:00:00,300.851667,300.749199,300.754456,300.949280
2017-04-30 07:00:00,NaN,NaN,300.549591,300.876801
2017-04-30 08:00:00,NaN,NaN,300.055878,300.483185
2017-04-30 09:00:00,NaN,NaN,299.370300,299.736145
2017-04-30 10:00:00,299.180930,298.983662,298.357666,298.592407
2017-04-30 11:00:00,NaN,NaN,296.698792,296.796783
2017-04-30 12:00:00,297.610000,296.853864,295.559814,295.628906
2017-04-30 13:00:00,NaN,NaN,294.873444,294.923828
2017-04-30 14:00:00,NaN,NaN,294.346649,294.395660
2017-04-30 15:00:00,NaN,NaN,293.949921,293.993225
2017-04-30 16:00:00,NaN,NaN,293.631104,293.691498
2017-04-30 17:00:00,NaN,NaN,293.364349,293.469299
2017-04-30 18:00:00,NaN,NaN,293.168274,293.306763
2017-04-30 19:00:00,NaN,NaN,293.045502,293.200073
2017-04-30 20:00:00,NaN,NaN,292.977875,293.141266
2017-04-30 21:00:00,NaN,NaN,292.943756,293.101868
2017-04-30 22:00:00,NaN,NaN,292.936859,293.061646
2017-04-30 23:00:00,NaN,NaN,293.739899,293.843628

In [99]:
fin[['temperature','Temperature2m','Temperature2m_prefcst']].sort_index().plot()

In [152]:
fin[['temperature','end var']].sort_index().plot()

In [94]:
from sklearn.metrics import mean_absolute_error,median_absolute_error

In [101]:
print('线性方案的平均绝对误差：',mean_absolute_error(res['temperature'],res['end var']),
      '线性方案的绝对误差中位数：',median_absolute_error(res['temperature'],res['end var']))
print('纯3km数值模式的24小时平均绝对误差：',mean_absolute_error(res['temperature'],res['Temperature2m']),
      '纯3km数值模式的24小时绝对误差中位数：',median_absolute_error(res['temperature'],res['Temperature2m']))
print('纯3km数值模式的48小时平均绝对误差：',mean_absolute_error(res['temperature'],res['Temperature2m_prefcst']),
      '纯3km数值模式的48小时绝对误差中位数：',median_absolute_error(res['temperature'],res['Temperature2m_prefcst']))

线性方案的平均绝对误差： 0.6794100452432723 线性方案的绝对误差中位数： 0.598464133791623
纯3km数值模式的24小时平均绝对误差： 0.9033707410752606 纯3km数值模式的24小时绝对误差中位数： 0.813294987754233
纯3km数值模式的48小时平均绝对误差： 1.2020320388074675 纯3km数值模式的48小时绝对误差中位数： 1.1226886192727363

In [ ]:
##########################
##########################
##########################

In [ ]:
#为了更详实的验证，添加了一块用现有模型不进行额外训练直接用5月份的模式预报结果进行预报验证。

In [7]:
path = 'I:\data_new_synop05'
filelist = os.listdir(path)
filelist.sort()

In [8]:
records05 = extract_obs_data(path,filelist)

one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record
one record

In [12]:
with open('records05.pkl','wb') as fp:
    pickle.dump(records05,fp)

In [19]:
df05 = pd.DataFrame(records05,columns=features).set_index('date')

In [22]:
fcstpath = os.path.abspath('I:\mars3km_00_48h/')

In [25]:
fcst_records05=[]
idx=0
for date in df05.index:
    validtime = date.to_pydatetime()
    fcst_date_before=date.date() - forcast_d
    fcst_date=dateparser.parse(date.date().strftime("%Y/%m/%d-%H:%M:%S"))
    fcst_date_before=dateparser.parse(fcst_date_before.strftime("%Y/%m/%d-%H:%M:%S"))
    
    timedelta = validtime - fcst_date
    timedelta_before = validtime - fcst_date_before
    
    timedelta=int(timedelta.total_seconds()/3600)
    timedelta_before=int(timedelta_before.total_seconds()/3600)
    
    filename1=fcstpath+os.sep+"%s%03d"%(fcst_date.strftime("%Y%m%d%H/mars3km%y%m%d%H"),timedelta)
    filename2=fcstpath+os.sep+"%s%03d"%(fcst_date_before.strftime("%Y%m%d%H/mars3km%y%m%d%H"),timedelta_before)
    if os.path.isfile(filename1) and os.path.isfile(filename2):
        f1=forcast_to_result(ctl,filename1,lonlat_in_guangdong)
        f2=forcast_to_result(ctl,filename2,lonlat_in_guangdong)
        fcst_records05.append(FcstSummary(
            date                   =validtime,
            CombinedRadarReflective=f1.cr,
            SurfacePressure        =f1.ps,
            SeaLevelPressure       =f1.psl,
            RelativeHumidity2m     =f1.rh2m,
            Temperature2m          =f1.t2m,
            SurfaceTemperature     =f1.ts,
            U_wind10m              =f1.u10m,
            V_wind10m              =f1.v10m,
            CombinedRadarReflective_prefcst=f2.cr,
            SurfacePressure_prefcst        =f2.ps,
            SeaLevelPressure_prefcst       =f2.psl,
            RelativeHumidity2m_prefcst     =f2.rh2m,
            Temperature2m_prefcst          =f2.t2m,
            SurfaceTemperature_prefcst     =f2.ts,
            U_wind10m_prefcst              =f2.u10m,
            V_wind10m_prefcst              =f2.v10m,
        ))
        idx+=1
        print('num:',idx)

num: 1
num: 2
num: 3
num: 4
num: 5
num: 6
num: 7
num: 8
num: 9
num: 10
num: 11
num: 12
num: 13
num: 14
num: 15
num: 16
num: 17
num: 18
num: 19
num: 20
num: 21
num: 22
num: 23
num: 24
num: 25
num: 26
num: 27
num: 28
num: 29
num: 30
num: 31
num: 32
num: 33
num: 34
num: 35
num: 36
num: 37
num: 38
num: 39
num: 40
num: 41
num: 42
num: 43
num: 44
num: 45
num: 46
num: 47
num: 48
num: 49
num: 50
num: 51
num: 52
num: 53
num: 54
num: 55
num: 56
num: 57
num: 58
num: 59
num: 60
num: 61
num: 62
num: 63
num: 64
num: 65
num: 66
num: 67
num: 68
num: 69
num: 70
num: 71
num: 72
num: 73
num: 74
num: 75
num: 76
num: 77
num: 78
num: 79
num: 80
num: 81
num: 82
num: 83
num: 84
num: 85
num: 86
num: 87
num: 88
num: 89
num: 90
num: 91
num: 92
num: 93
num: 94
num: 95
num: 96
num: 97
num: 98
num: 99
num: 100
num: 101
num: 102
num: 103
num: 104
num: 105
num: 106
num: 107
num: 108
num: 109
num: 110
num: 111
num: 112
num: 113
num: 114
num: 115
num: 116
num: 117
num: 118
num: 119
num: 120
num: 121
num: 122
num: 123
num: 124
num: 125
num: 126
num: 127
num: 128
num: 129
num: 130
num: 131
num: 132
num: 133
num: 134
num: 135
num: 136
num: 137
num: 138
num: 139
num: 140
num: 141
num: 142
num: 143
num: 144
num: 145
num: 146
num: 147
num: 148
num: 149
num: 150
num: 151
num: 152
num: 153
num: 154
num: 155
num: 156
num: 157
num: 158
num: 159
num: 160
num: 161
num: 162
num: 163
num: 164
num: 165
num: 166
num: 167
num: 168
num: 169
num: 170
num: 171
num: 172
num: 173
num: 174
num: 175
num: 176
num: 177
num: 178
num: 179
num: 180
num: 181
num: 182
num: 183
num: 184
num: 185
num: 186
num: 187
num: 188
num: 189
num: 190
num: 191
num: 192
num: 193
num: 194
num: 195
num: 196
num: 197
num: 198
num: 199
num: 200
num: 201
num: 202
num: 203
num: 204
num: 205
num: 206
num: 207
num: 208
num: 209
num: 210
num: 211
num: 212
num: 213
num: 214
num: 215
num: 216
num: 217
num: 218
num: 219
num: 220
num: 221
num: 222
num: 223
num: 224
num: 225
num: 226
num: 227
num: 228
num: 229
num: 230
num: 231
num: 232
num: 233
num: 234
num: 235
num: 236
num: 237
num: 238
num: 239
num: 240
num: 241
num: 242
num: 243
num: 244
num: 245
num: 246
num: 247
num: 248
num: 249
num: 250
num: 251
num: 252
num: 253
num: 254
num: 255
num: 256
num: 257
num: 258
num: 259
num: 260
num: 261
num: 262
num: 263
num: 264
num: 265
num: 266
num: 267
num: 268
num: 269
num: 270
num: 271
num: 272
num: 273
num: 274
num: 275
num: 276
num: 277
num: 278
num: 279
num: 280
num: 281
num: 282
num: 283
num: 284
num: 285
num: 286
num: 287
num: 288
num: 289
num: 290
num: 291
num: 292
num: 293
num: 294
num: 295
num: 296
num: 297
num: 298
num: 299
num: 300
num: 301
num: 302
num: 303
num: 304
num: 305
num: 306
num: 307
num: 308
num: 309
num: 310
num: 311
num: 312
num: 313
num: 314
num: 315
num: 316
num: 317
num: 318
num: 319
num: 320
num: 321
num: 322
num: 323
num: 324
num: 325
num: 326
num: 327
num: 328
num: 329
num: 330
num: 331
num: 332
num: 333
num: 334
num: 335
num: 336
num: 337
num: 338
num: 339
num: 340
num: 341
num: 342
num: 343
num: 344
num: 345
num: 346
num: 347
num: 348
num: 349
num: 350
num: 351
num: 352
num: 353
num: 354
num: 355
num: 356
num: 357
num: 358
num: 359
num: 360
num: 361
num: 362
num: 363
num: 364
num: 365
num: 366
num: 367
num: 368
num: 369
num: 370
num: 371
num: 372
num: 373
num: 374
num: 375
num: 376
num: 377
num: 378
num: 379
num: 380
num: 381
num: 382
num: 383
num: 384
num: 385
num: 386
num: 387
num: 388
num: 389
num: 390
num: 391
num: 392
num: 393
num: 394
num: 395
num: 396
num: 397
num: 398
num: 399
num: 400
num: 401
num: 402
num: 403
num: 404
num: 405
num: 406
num: 407
num: 408
num: 409
num: 410
num: 411
num: 412
num: 413
num: 414
num: 415
num: 416
num: 417
num: 418
num: 419
num: 420
num: 421
num: 422
num: 423
num: 424
num: 425
num: 426
num: 427
num: 428
num: 429
num: 430
num: 431
num: 432
num: 433
num: 434
num: 435
num: 436
num: 437
num: 438
num: 439
num: 440
num: 441
num: 442
num: 443
num: 444
num: 445
num: 446
num: 447
num: 448
num: 449
num: 450
num: 451
num: 452
num: 453
num: 454
num: 455
num: 456
num: 457
num: 458
num: 459
num: 460
num: 461
num: 462
num: 463
num: 464
num: 465
num: 466
num: 467
num: 468
num: 469
num: 470
num: 471
num: 472
num: 473
num: 474
num: 475
num: 476
num: 477
num: 478
num: 479
num: 480
num: 481
num: 482
num: 483
num: 484
num: 485
num: 486
num: 487
num: 488
num: 489
num: 490
num: 491
num: 492
num: 493
num: 494
num: 495
num: 496
num: 497
num: 498
num: 499
num: 500
num: 501
num: 502
num: 503
num: 504
num: 505
num: 506
num: 507
num: 508
num: 509
num: 510
num: 511
num: 512
num: 513
num: 514
num: 515
num: 516
num: 517
num: 518
num: 519
num: 520
num: 521
num: 522
num: 523
num: 524
num: 525
num: 526
num: 527
num: 528
num: 529
num: 530
num: 531
num: 532
num: 533
num: 534
num: 535
num: 536
num: 537
num: 538
num: 539
num: 540
num: 541
num: 542
num: 543
num: 544
num: 545
num: 546
num: 547
num: 548
num: 549
num: 550
num: 551
num: 552
num: 553
num: 554
num: 555
num: 556
num: 557
num: 558
num: 559
num: 560
num: 561
num: 562
num: 563
num: 564
num: 565
num: 566
num: 567
num: 568
num: 569
num: 570
num: 571
num: 572
num: 573
num: 574
num: 575
num: 576
num: 577
num: 578
num: 579
num: 580
num: 581
num: 582
num: 583
num: 584
num: 585
num: 586
num: 587
num: 588
num: 589
num: 590
num: 591
num: 592
num: 593
num: 594
num: 595
num: 596
num: 597
num: 598
num: 599
num: 600
num: 601
num: 602
num: 603
num: 604
num: 605
num: 606
num: 607
num: 608
num: 609
num: 610
num: 611
num: 612
num: 613
num: 614
num: 615
num: 616
num: 617
num: 618
num: 619
num: 620
num: 621
num: 622
num: 623
num: 624
num: 625
num: 626
num: 627
num: 628
num: 629
num: 630
num: 631
num: 632
num: 633
num: 634
num: 635
num: 636
num: 637
num: 638
num: 639
num: 640
num: 641
num: 642
num: 643
num: 644
num: 645
num: 646
num: 647
num: 648
num: 649
num: 650
num: 651
num: 652
num: 653
num: 654
num: 655
num: 656
num: 657
num: 658
num: 659
num: 660
num: 661
num: 662
num: 663
num: 664
num: 665
num: 666
num: 667
num: 668
num: 669
num: 670
num: 671
num: 672
num: 673
num: 674
num: 675
num: 676
num: 677
num: 678

In [27]:
with open('fcst_records05.pkl','wb') as fp:
    pickle.dump(fcst_records05,fp)

In [38]:
with open('fcst_records05.pkl','rb') as fp:
    fcst_records05=pickle.load(fp)
    
with open('records05.pkl','rb') as fp:
    records05=pickle.load(fp)

In [57]:
df_fcst05 = pd.DataFrame(fcst_records05,columns=fcst_features).set_index('date')
for feature in fcst_features:
    if feature != 'date':
        for N in range(1,4):
            derive_ntime_feature(df_fcst05,feature,N)

df05 = pd.DataFrame(records05,columns=features).set_index('date')
df_all05 = pd.concat([df05['temperature'],df_fcst05[X_test.columns],df_fcst05['Temperature2m_prefcst']],axis=1).dropna()

In [62]:
prediction05=regressor.predict(df_all05[X_test.columns])
res05 = pd.concat([df_all05[['temperature','Temperature2m','Temperature2m_prefcst']],pd.DataFrame({'end_var':prediction05},index=df_all05.index)],axis=1)
res05 = res05 - 273.15

In [63]:
res05.plot()

In [61]:
from sklearn.metrics import mean_absolute_error,median_absolute_error
print('线性方案的平均绝对误差：',mean_absolute_error(res05['temperature'],res05['end_var']),
      '线性方案的绝对误差中位数：',median_absolute_error(res05['temperature'],res05['end_var']))
print('纯3km数值模式的24小时平均绝对误差：',mean_absolute_error(res05['temperature'],res05['Temperature2m']),
      '纯3km数值模式的24小时绝对误差中位数：',median_absolute_error(res05['temperature'],res05['Temperature2m']))
print('纯3km数值模式的48小时平均绝对误差：',mean_absolute_error(res05['temperature'],res05['Temperature2m_prefcst']),
      '纯3km数值模式的48小时绝对误差中位数：',median_absolute_error(res05['temperature'],res05['Temperature2m_prefcst']))

线性方案的平均绝对误差： 0.8157841609809573 线性方案的绝对误差中位数： 0.731798992141421
纯3km数值模式的24小时平均绝对误差： 1.0200630563686308 纯3km数值模式的24小时绝对误差中位数： 0.9635428133877895
纯3km数值模式的48小时平均绝对误差： 1.2639288400894908 纯3km数值模式的48小时绝对误差中位数： 1.224324625651036